name: 'CBAE action'
description: 'Performs CBOM vulnerability analysis on a repository using CLI and provides a detailed compliance report.'
author: 'Namokar'

inputs:
  token:
    description: 'GitHub token with access to clone CBOM tool repo'
    required: true
  commands-to-install-build-tools:
    description: 'Optional shell commands to install custom build tools before analysis'
    required: false
  build-command:
    description: 'Optional build command to compile the project before analysis'
    required: false

outputs:
  cbom-report:
    description: 'Path to the generated CBOM JSON report'
  compliance-report:
    description: 'Path to the generated compliance text report'

runs:
  using: "composite"
  steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Essential Build Tools
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          python3-dev python3-venv git curl build-essential

    - name: Run user-provided build tool install commands
      if: inputs.commands-to-install-build-tools != ''
      shell: bash
      run: |
        echo "Running user-provided build tool commands..."
        eval "${{ inputs.commands-to-install-build-tools }}"

    - name: Installing default tools
      shell: bash
      run: |
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config cmake clang gcc g++ make
        sudo apt-get install -y libssl-dev zlib1g-dev libnghttp2-dev
        sudo apt-get install -y libpsl-dev libidn2-dev libssh2-1-dev
        sudo apt-get install -y libkrb5-dev librtmp-dev libldap2-dev
        sudo apt-get install -y libgnutls28-dev libcurl4-openssl-dev

    - name: Setup CodeQL CLI
      shell: bash
      run: |
        mkdir -p $HOME/codeql-cli
        wget -q https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.21.3/codeql-bundle-linux64.tar.gz -O codeql-bundle.tar.gz
        tar -xzf codeql-bundle.tar.gz -C $HOME/codeql-cli
        CODEQL_PATH=$(find $HOME/codeql-cli -name codeql -type f | head -n 1)
        CODEQL_DIR=$(dirname "$CODEQL_PATH")
        echo "CODEQL_PATH=${CODEQL_PATH}" >> $GITHUB_ENV
        echo "CODEQL_DIR=${CODEQL_DIR}" >> $GITHUB_ENV
        echo "${CODEQL_DIR}" >> $GITHUB_PATH
        "${CODEQL_PATH}" --version

    - name: Clone CBOM Tool
      uses: actions/checkout@v4
      with:
        repository: Namokar100/tool
        path: .cbom-tool
        token: ${{ inputs.token }}

    - name: Install CBOM Tool Dependencies
      shell: bash
      run: |
        cd .cbom-tool
        python -m pip install --upgrade pip setuptools wheel
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -e .

    - name: Create Output Directory
      shell: bash
      run: mkdir -p analysis-results

    - name: Run CBOM Analysis
      shell: bash
      run: |
        cd .cbom-tool
        source venv/bin/activate
        REPO_PATH="${{ github.workspace }}"
        RULES_PATH="${{ github.workspace }}/.cbom-tool/data/default_rules.yaml"

        if [[ "${{ inputs.build-command }}" != "" ]]; then
          BUILD_CMD="${{ inputs.build-command }}"
        else
          BUILD_CMD="autoreconf -fi && ./configure --with-openssl && make -j$(nproc)"
        fi

        python calyptra_ql/cli.py \
          "${REPO_PATH}" \
          --build-command "${BUILD_CMD}" \
          -o "${{ github.workspace }}/analysis-results/cbom.json" \
          -c "${{ github.workspace }}/analysis-results/compliance_report.txt" \
          --rules "${RULES_PATH}" \
          -vv

    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: cbom-analysis-results
        path: |
          analysis-results/cbom.json
          analysis-results/compliance_report.txt

    - name: Set Outputs
      shell: bash
      run: |
        echo "cbom-report=analysis-results/cbom.json" >> $GITHUB_OUTPUT
        echo "compliance-report=analysis-results/compliance_report.txt" >> $GITHUB_OUTPUT

    - name: Check for Vulnerabilities and Fail if Found
      shell: bash
      run: |
        REPORT_PATH="analysis-results/compliance_report.txt"
        if [ ! -f "$REPORT_PATH" ]; then
          echo "::error::Compliance report not found"
          exit 1
        fi

        VIOLATIONS=$(grep -c '^- Rule ID:' "$REPORT_PATH")
        if [ "$VIOLATIONS" -gt 0 ]; then
          echo "::warning::Found $VIOLATIONS violations. Failing the job."
          exit 1
        fi 

    - name: Create Detailed Summary
      shell: bash
      if: always()
      run: |
        cd ${{ github.workspace }}
        REPORT_PATH="analysis-results/compliance_report.txt"

        echo "## CBOM Analysis Results" >> $GITHUB_STEP_SUMMARY
        echo "Analysis completed at: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "### Repository Analyzed" >> $GITHUB_STEP_SUMMARY
        echo "Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "Branch: ${GITHUB_REF#refs/heads/}" >> $GITHUB_STEP_SUMMARY
        echo "Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ ! -f "$REPORT_PATH" ]; then
          echo "### Compliance report not found." >> $GITHUB_STEP_SUMMARY
          echo "No violations found." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Full Reports" >> $GITHUB_STEP_SUMMARY
          echo "Detailed reports are available in the workflow artifacts:" >> $GITHUB_STEP_SUMMARY
          echo "- CBOM Report (cbom.json)" >> $GITHUB_STEP_SUMMARY
          echo "- Compliance Report (compliance_report.txt)" >> $GITHUB_STEP_SUMMARY
          exit 0
        fi

        TOTAL_VIOLATIONS=$(grep "Found [0-9]* violation" "$REPORT_PATH" | grep -o '[0-9]*' | head -1)
        if [ -z "$TOTAL_VIOLATIONS" ]; then
          TOTAL_VIOLATIONS=0
        fi

        echo "### Security Violations Found" >> $GITHUB_STEP_SUMMARY
        echo "**Total violations found: $TOTAL_VIOLATIONS**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ "$TOTAL_VIOLATIONS" -gt 0 ]; then
          awk '
            BEGIN {
              violation_count = 0
              in_violation = 0
            }
            /^- Rule ID:/ {
              in_violation = 1
              rule_id = $0
              gsub(/^- Rule ID:[[:space:]]*/, "", rule_id)
            }
            in_violation && /^  Description:/ {
              description = $0
              gsub(/^  Description:[[:space:]]*/, "", description)
            }
            in_violation && /^  Location:/ {
              location = $0
              gsub(/^  Location:[[:space:]]*/, "", location)
              split(location, loc_parts, ":")
              file = loc_parts[1]
              line = loc_parts[2]
            }
            in_violation && /^  Finding:/ {
              finding = $0
              gsub(/^  Finding:[[:space:]]*/, "", finding)
            }
            in_violation && /^$/ {
              if (rule_id && description && file && line) {
                violation_count++

                severity = "Medium"
                if (index(description, "DES") > 0) severity = "High"
                if (index(description, "MD5") > 0) severity = "Medium"
                if (index(description, "SHA1") > 0) severity = "Medium"
                if (index(description, "RC4") > 0) severity = "High"

                print "#### Violation in `" file "` at line " line
                print "**Rule**: " rule_id
                print "**Severity**: " severity
                print "**Description**: " description
                print ""
                print "**Affected Code:**"
                print "```c"

                start_line = line - 3
                end_line = line + 3
                if (start_line < 1) start_line = 1

                cmd = "awk -v start=" start_line " -v end=" end_line " -v target=" line " '\''NR >= start && NR <= end { if (NR == target) { printf \"→ %d: %s\\n\", NR, $0 } else { printf \"  %d: %s\\n\", NR, $0 } }'\'' " file
                if (system("test -f " file) == 0) {
                  system(cmd)
                } else {
                  print "File not found in workspace."
                }

                print "```"
                print ""

                if (severity == "High") high_count++
                else if (severity == "Medium") medium_count++
                else if (severity == "Low") low_count++
              }
              in_violation = 0
              rule_id = ""
              description = ""
              location = ""
              file = ""
              line = ""
              finding = ""
            }
            END {
              print "### Violation Statistics"
              print "**Total violations**: " violation_count
              print ""
              print "**By severity:**"
              if (high_count > 0) print "- High: " high_count
              if (medium_count > 0) print "- Medium: " medium_count
              if (low_count > 0) print "- Low: " low_count
              print ""
            }
          ' "$REPORT_PATH" >> $GITHUB_STEP_SUMMARY
        else
          echo "No violations found." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        echo "### Full Reports" >> $GITHUB_STEP_SUMMARY
        echo "Detailed reports are available in the workflow artifacts:" >> $GITHUB_STEP_SUMMARY
        echo "- CBOM Report (cbom.json)" >> $GITHUB_STEP_SUMMARY
        echo "- Compliance Report (compliance_report.txt)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Job summary generated at run-time**" >> $GITHUB_STEP_SUMMARY

